#!/bin/sh

test -f /etc/vz/vzstats-disable && exit 0

. /etc/vz/vzstats.conf
IDFILE=/etc/vz/.vzstats-uuid
VERSION=0.2.1

# Autodiscover proxy
discover_proxy() {
	local proxy_line

	if [ ! -z "$http_proxy" ]; then
		return
	fi

	if [ -r "/etc/wgetrc" ];then
		proxy_line=$(grep '^http_proxy' /etc/wgetrc | tr -d ' \t');
		if [ ! -z $proxy_line ]; then
			export $proxy_line
			return
		fi
	fi

	if [ -r "/etc/yum.conf" ];then
		proxy_line=$(grep '^proxy=' /etc/yum.conf);
		if [ ! -z $proxy_line ]; then
			proxy_line=http_$proxy_line
			export $proxy_line
			return
		fi
	fi
}

discover_proxy
CURL='curl -sS --connect-timeout 3'
OPT_VIEW=

# Check that config is sufficient
set -u
echo $REP_DIR $SUBMIT_URL >/dev/null
# Check that scripts directory exist and is not empty
ls $REP_DIR/* >/dev/null || exit 1

usage() {
	cat << EOF
vzstats version $VERSION

Usage:
	vzstats [option]

Options:
	--view		do not send any stats, just see what would be send
	--help		see this help
EOF

	exit $1
}

case $1 in
	--view)
		OPT_VIEW=yes
		;;
	-h|-?|--help)
		usage 0
		;;
	*)
		usage 1
		;;
esac

err() {
	echo "$*, aborting" 2>&1
	exit 1
}

check_id() {
	if ! echo $1 | grep -qiE '^\{?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\}?$'; then
		rm -f $IDFILE
		err "Invalid UUID $1"
	fi
}

get_id() {
	local id

	if test -f $IDFILE; then
		id=$(cat $IDFILE)
	else
		# Check that IDFILE is writeable
		echo > $IDFILE || exit 1
		id=$(${CURL} -F magic_word=very-please $GET_ID_URL)
		echo $id > $IDFILE || exit 1
	fi

	check_id "$id"
	UUID=$id
}

get_id

OUTDIR=$(mktemp -d)
OUT=$(mktemp)
trap "rm -fr $OUTDIR $OUT" INT TERM EXIT
SCRIPTS=$(find $REP_DIR -maxdepth 1 -type f -user 0 -group 0 \
	-perm -u+rx -not -perm -g+w -not -perm -o+w \
	-print | sort)

if test -z "$SCRIPTS"; then
	err "No scripts found in $REP_DIR"
fi


LOG=collect.log
echo "== vzstats $VERSION ==" > $OUTDIR/$LOG
for S in $SCRIPTS; do
	NAME=$(basename $S)
	echo "== executing $S ==" >> $OUTDIR/$LOG
	$S > $OUTDIR/$NAME 2>>$OUTDIR/$LOG
done

if [ -n "$OPT_VIEW" ]; then
	# Just view, do not set report
	echo "View mode enabled -- not sending report to $SUBMIT_URL"
	echo "To review what information would be sent, see $OUTDIR"
	echo "Do not forget to remove it afterwards"
	trap "" INT TERM EXIT
	exit 0
fi
tar czf $OUT -C $OUTDIR . || exit 1
${CURL} -F uuid=$UUID -F file=@${OUT} $SUBMIT_URL
